[project]
name = "pipecat-bot"
version = "0.1.0"
description = "Simple Gladia transcriber example using Pipecat"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pipecat-ai[webrtc,gladia,runner,silero]>=0.0.82,<0.1.0"
]
